#if !canImport(ObjectiveC)
import XCTest

extension ASMTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ASMTests = [
        ("testEncoding", testEncoding),
        ("testInitialization", testInitialization),
        ("testValidation", testValidation),
    ]
}

extension AddGlobalUnsubscribesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddGlobalUnsubscribesTests = [
        ("testInitialization", testInitialization),
    ]
}

extension AddressTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddressTests = [
        ("testEncoding", testEncoding),
        ("testInitialization", testInitialization),
        ("testValidation", testValidation),
    ]
}

extension AttachmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttachmentTests = [
        ("testEncoding", testEncoding),
        ("testInitialization", testInitialization),
        ("testValidation", testValidation),
    ]
}

extension AuthenticationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthenticationTests = [
        ("testApiKey", testApiKey),
        ("testAuthorizationHeader", testAuthorizationHeader),
        ("testCredential", testCredential),
        ("testInitializer", testInitializer),
    ]
}

extension BCCSettingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BCCSettingTests = [
        ("testEncoding", testEncoding),
        ("testValidation", testValidation),
    ]
}

extension BlockTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BlockTests = [
        ("testInitialization", testInitialization),
    ]
}

extension BounceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BounceTests = [
        ("testInitialization", testInitialization),
    ]
}

extension BypassListManagementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BypassListManagementTests = [
        ("testEncoding", testEncoding),
    ]
}

extension ClickTrackingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClickTrackingTests = [
        ("testExample", testExample),
    ]
}

extension ContentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContentTests = [
        ("testClassInitializers", testClassInitializers),
        ("testEncoding", testEncoding),
        ("testInitialization", testInitialization),
        ("testValidation", testValidation),
    ]
}

extension ContentTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContentTypeTests = [
        ("testEncoding", testEncoding),
        ("testIndex", testIndex),
        ("testInitializerAndDescription", testInitializerAndDescription),
        ("testRawInitializer", testRawInitializer),
    ]
}

extension DeleteBlocksTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteBlocksTests = [
        ("testDeleteAll", testDeleteAll),
        ("testInitializer", testInitializer),
    ]
}

extension DeleteBouncesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteBouncesTests = [
        ("testDeleteAll", testDeleteAll),
        ("testInitializer", testInitializer),
    ]
}

extension DeleteGlobalUnsubscribeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteGlobalUnsubscribeTests = [
        ("testInitializer", testInitializer),
    ]
}

extension DeleteInvalidEmailsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteInvalidEmailsTests = [
        ("testDeleteAll", testDeleteAll),
        ("testInitializer", testInitializer),
    ]
}

extension DeleteSpamReportsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeleteSpamReportsTests = [
        ("testDeleteAll", testDeleteAll),
        ("testInitializer", testInitializer),
    ]
}

extension EmailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmailTests = [
        ("testCategoryValidation", testCategoryValidation),
        ("testContentValidation", testContentValidation),
        ("testCustomArgs", testCustomArgs),
        ("testEncoding", testEncoding),
        ("testHeaderValidation", testHeaderValidation),
        ("testInitialization", testInitialization),
        ("testNoImpersonation", testNoImpersonation),
        ("testOnlyApiKeys", testOnlyApiKeys),
        ("testPersonalizationValidation", testPersonalizationValidation),
        ("testSendAt", testSendAt),
        ("testSubjectValidation", testSubjectValidation),
    ]
}

extension FooterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FooterTests = [
        ("testEncoding", testEncoding),
    ]
}

extension GlobalUnsubscribeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GlobalUnsubscribeTests = [
        ("testInitialization", testInitialization),
    ]
}

extension GoogleAnalyticsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GoogleAnalyticsTests = [
        ("testEncoding", testEncoding),
    ]
}

extension HTTPMethodTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPMethodTests = [
        ("testDescription", testDescription),
        ("testHasBody", testHasBody),
    ]
}

extension InvalidEmailTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InvalidEmailTests = [
        ("testInitialization", testInitialization),
    ]
}

extension MailSettingsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MailSettingsTests = [
        ("testEncoding", testEncoding),
        ("testValidation", testValidation),
    ]
}

extension OpenTrackingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OpenTrackingTests = [
        ("testEncoding", testEncoding),
    ]
}

extension PaginationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PaginationTests = [
        ("testBadHeaders", testBadHeaders),
        ("testNoHeader", testNoHeader),
        ("testUrlResponseInit", testUrlResponseInit),
    ]
}

extension PersonalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersonalizationTests = [
        ("testEncoding", testEncoding),
        ("testInitialization", testInitialization),
        ("testValidation", testValidation),
    ]
}

extension RateLimitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RateLimitTests = [
        ("testBadHeaders", testBadHeaders),
        ("testUrlResponseInitializer", testUrlResponseInitializer),
    ]
}

extension RetrieveBlocksTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveBlocksTests = [
        ("testEmailSpecificInitializer", testEmailSpecificInitializer),
        ("testGetAllInitialization", testGetAllInitialization),
        ("testValidation", testValidation),
    ]
}

extension RetrieveBouncesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveBouncesTests = [
        ("testEmailSpecificInitializer", testEmailSpecificInitializer),
        ("testGetAllInitialization", testGetAllInitialization),
        ("testValidation", testValidation),
    ]
}

extension RetrieveCategoryStatisticsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveCategoryStatisticsTests = [
        ("testMaxInitialization", testMaxInitialization),
        ("testMinimalInitialization", testMinimalInitialization),
        ("testValidation", testValidation),
    ]
}

extension RetrieveGlobalStatisticsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveGlobalStatisticsTests = [
        ("testMaxInitialization", testMaxInitialization),
        ("testMinimalInitialization", testMinimalInitialization),
        ("testValidation", testValidation),
    ]
}

extension RetrieveGlobalUnsubscribesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveGlobalUnsubscribesTests = [
        ("testEmailSpecificInitializer", testEmailSpecificInitializer),
        ("testGetAllInitialization", testGetAllInitialization),
        ("testValidation", testValidation),
    ]
}

extension RetrieveInvalidEmailsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveInvalidEmailsTests = [
        ("testEmailSpecificInitializer", testEmailSpecificInitializer),
        ("testGetAllInitialization", testGetAllInitialization),
        ("testValidation", testValidation),
    ]
}

extension RetrieveSpamReportsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveSpamReportsTests = [
        ("testEmailSpecificInitializer", testEmailSpecificInitializer),
        ("testGetAllInitialization", testGetAllInitialization),
        ("testValidation", testValidation),
    ]
}

extension RetrieveSubuserStatisticsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveSubuserStatisticsTests = [
        ("testMaxInitialization", testMaxInitialization),
        ("testMinimalInitialization", testMinimalInitialization),
        ("testValidation", testValidation),
    ]
}

extension RetrieveSubusersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RetrieveSubusersTests = [
        ("testInitialization", testInitialization),
        ("testValidation", testValidation),
    ]
}

extension SandboxModeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SandboxModeTests = [
        ("testEncoding", testEncoding),
    ]
}

extension SessionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SessionTests = [
        ("testSendWithoutAuth", testSendWithoutAuth),
    ]
}

extension SpamCheckerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpamCheckerTests = [
        ("testEncoding", testEncoding),
        ("testInitialization", testInitialization),
        ("testValidation", testValidation),
    ]
}

extension SpamReportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpamReportTests = [
        ("testInitialization", testInitialization),
    ]
}

extension SubscriptionTrackingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubscriptionTrackingTests = [
        ("testEncoding", testEncoding),
        ("testValidation", testValidation),
    ]
}

extension SuppressionListDeleterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SuppressionListDeleterTests = [
        ("testInitialization", testInitialization),
    ]
}

extension SuppressionListReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SuppressionListReaderTests = [
        ("testInitialization", testInitialization),
    ]
}

extension TrackingSettingsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TrackingSettingsTests = [
        ("testEncoding", testEncoding),
        ("testValidation", testValidation),
    ]
}

extension ValidateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidateTests = [
        ("testEmail", testEmail),
        ("testInput", testInput),
        ("testNoCLRF", testNoCLRF),
        ("testSubscriptionTracking", testSubscriptionTracking),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ASMTests.__allTests__ASMTests),
        testCase(AddGlobalUnsubscribesTests.__allTests__AddGlobalUnsubscribesTests),
        testCase(AddressTests.__allTests__AddressTests),
        testCase(AttachmentTests.__allTests__AttachmentTests),
        testCase(AuthenticationTests.__allTests__AuthenticationTests),
        testCase(BCCSettingTests.__allTests__BCCSettingTests),
        testCase(BlockTests.__allTests__BlockTests),
        testCase(BounceTests.__allTests__BounceTests),
        testCase(BypassListManagementTests.__allTests__BypassListManagementTests),
        testCase(ClickTrackingTests.__allTests__ClickTrackingTests),
        testCase(ContentTests.__allTests__ContentTests),
        testCase(ContentTypeTests.__allTests__ContentTypeTests),
        testCase(DeleteBlocksTests.__allTests__DeleteBlocksTests),
        testCase(DeleteBouncesTests.__allTests__DeleteBouncesTests),
        testCase(DeleteGlobalUnsubscribeTests.__allTests__DeleteGlobalUnsubscribeTests),
        testCase(DeleteInvalidEmailsTests.__allTests__DeleteInvalidEmailsTests),
        testCase(DeleteSpamReportsTests.__allTests__DeleteSpamReportsTests),
        testCase(EmailTests.__allTests__EmailTests),
        testCase(FooterTests.__allTests__FooterTests),
        testCase(GlobalUnsubscribeTests.__allTests__GlobalUnsubscribeTests),
        testCase(GoogleAnalyticsTests.__allTests__GoogleAnalyticsTests),
        testCase(HTTPMethodTests.__allTests__HTTPMethodTests),
        testCase(InvalidEmailTests.__allTests__InvalidEmailTests),
        testCase(MailSettingsTests.__allTests__MailSettingsTests),
        testCase(OpenTrackingTests.__allTests__OpenTrackingTests),
        testCase(PaginationTests.__allTests__PaginationTests),
        testCase(PersonalizationTests.__allTests__PersonalizationTests),
        testCase(RateLimitTests.__allTests__RateLimitTests),
        testCase(RetrieveBlocksTests.__allTests__RetrieveBlocksTests),
        testCase(RetrieveBouncesTests.__allTests__RetrieveBouncesTests),
        testCase(RetrieveCategoryStatisticsTests.__allTests__RetrieveCategoryStatisticsTests),
        testCase(RetrieveGlobalStatisticsTests.__allTests__RetrieveGlobalStatisticsTests),
        testCase(RetrieveGlobalUnsubscribesTests.__allTests__RetrieveGlobalUnsubscribesTests),
        testCase(RetrieveInvalidEmailsTests.__allTests__RetrieveInvalidEmailsTests),
        testCase(RetrieveSpamReportsTests.__allTests__RetrieveSpamReportsTests),
        testCase(RetrieveSubuserStatisticsTests.__allTests__RetrieveSubuserStatisticsTests),
        testCase(RetrieveSubusersTests.__allTests__RetrieveSubusersTests),
        testCase(SandboxModeTests.__allTests__SandboxModeTests),
        testCase(SessionTests.__allTests__SessionTests),
        testCase(SpamCheckerTests.__allTests__SpamCheckerTests),
        testCase(SpamReportTests.__allTests__SpamReportTests),
        testCase(SubscriptionTrackingTests.__allTests__SubscriptionTrackingTests),
        testCase(SuppressionListDeleterTests.__allTests__SuppressionListDeleterTests),
        testCase(SuppressionListReaderTests.__allTests__SuppressionListReaderTests),
        testCase(TrackingSettingsTests.__allTests__TrackingSettingsTests),
        testCase(ValidateTests.__allTests__ValidateTests),
    ]
}
#endif
